//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mx.Broker.Std.Request.Interface.PostTapingCollectShuttle01
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostTapingCollectShuttleLayerDestinationRequest", Namespace="http://schemas.datacontract.org/2004/07/Mx.Broker.Std.Request.Interface.PostTapin" +
        "gCollectShuttle01")]
    public partial class PostTapingCollectShuttleLayerDestinationRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MissionNumberField;
        
        private int SorterInputConveyorNumberField;
        
        private int TapingOutputConveyorNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MissionNumber
        {
            get
            {
                return this.MissionNumberField;
            }
            set
            {
                this.MissionNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SorterInputConveyorNumber
        {
            get
            {
                return this.SorterInputConveyorNumberField;
            }
            set
            {
                this.SorterInputConveyorNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TapingOutputConveyorNumber
        {
            get
            {
                return this.TapingOutputConveyorNumberField;
            }
            set
            {
                this.TapingOutputConveyorNumberField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IInterfacesMxToPostTapingCollectShuttle01")]
public interface IInterfacesMxToPostTapingCollectShuttle01
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacesMxToPostTapingCollectShuttle01/LayerDestination", ReplyAction="http://tempuri.org/IInterfacesMxToPostTapingCollectShuttle01/LayerDestinationResp" +
        "onse")]
    void LayerDestination(Mx.Broker.Std.Request.Interface.PostTapingCollectShuttle01.PostTapingCollectShuttleLayerDestinationRequest request);
}
