//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace collectns
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostTapingCollectShuttleLayerDestinationRequest", Namespace="http://schemas.datacontract.org/2004/07/Mx.Broker.Std.Request.Interface.PostTapin" +
        "gCollectShuttle01")]
    public partial class PostTapingCollectShuttleLayerDestinationRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MissionNumberField;
        
        private int SorterInputConveyorNumberField;
        
        private int TapingOutputConveyorNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MissionNumber
        {
            get
            {
                return this.MissionNumberField;
            }
            set
            {
                this.MissionNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SorterInputConveyorNumber
        {
            get
            {
                return this.SorterInputConveyorNumberField;
            }
            set
            {
                this.SorterInputConveyorNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TapingOutputConveyorNumber
        {
            get
            {
                return this.TapingOutputConveyorNumberField;
            }
            set
            {
                this.TapingOutputConveyorNumberField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="collectns.IInterfacesMxToPostTapingCollectShuttle01")]
    public interface IInterfacesMxToPostTapingCollectShuttle01
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacesMxToPostTapingCollectShuttle01/LayerDestination", ReplyAction="http://tempuri.org/IInterfacesMxToPostTapingCollectShuttle01/LayerDestinationResp" +
            "onse")]
        void LayerDestination(collectns.PostTapingCollectShuttleLayerDestinationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacesMxToPostTapingCollectShuttle01/LayerDestination", ReplyAction="http://tempuri.org/IInterfacesMxToPostTapingCollectShuttle01/LayerDestinationResp" +
            "onse")]
        System.Threading.Tasks.Task LayerDestinationAsync(collectns.PostTapingCollectShuttleLayerDestinationRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInterfacesMxToPostTapingCollectShuttle01Channel : collectns.IInterfacesMxToPostTapingCollectShuttle01, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InterfacesMxToPostTapingCollectShuttle01Client : System.ServiceModel.ClientBase<collectns.IInterfacesMxToPostTapingCollectShuttle01>, collectns.IInterfacesMxToPostTapingCollectShuttle01
    {
        
        public InterfacesMxToPostTapingCollectShuttle01Client()
        {
        }
        
        public InterfacesMxToPostTapingCollectShuttle01Client(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public InterfacesMxToPostTapingCollectShuttle01Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public InterfacesMxToPostTapingCollectShuttle01Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public InterfacesMxToPostTapingCollectShuttle01Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void LayerDestination(collectns.PostTapingCollectShuttleLayerDestinationRequest request)
        {
            base.Channel.LayerDestination(request);
        }
        
        public System.Threading.Tasks.Task LayerDestinationAsync(collectns.PostTapingCollectShuttleLayerDestinationRequest request)
        {
            return base.Channel.LayerDestinationAsync(request);
        }
    }
}
