//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace evacuationns
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostTapingEvacuationShuttleLayerEvacuationRequest", Namespace="http://schemas.datacontract.org/2004/07/Mx.Broker.Std.Request.Interface.PostTapin" +
        "gEvacuationShuttle01")]
    public partial class PostTapingEvacuationShuttleLayerEvacuationRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int LayerDestinationField;
        
        private int MissionNumberField;
        
        private int SorterOutputConveyorNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LayerDestination
        {
            get
            {
                return this.LayerDestinationField;
            }
            set
            {
                this.LayerDestinationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MissionNumber
        {
            get
            {
                return this.MissionNumberField;
            }
            set
            {
                this.MissionNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SorterOutputConveyorNumber
        {
            get
            {
                return this.SorterOutputConveyorNumberField;
            }
            set
            {
                this.SorterOutputConveyorNumberField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="evacuationns.IInterfacesMxToPostTapingEvacuationShuttle01")]
    public interface IInterfacesMxToPostTapingEvacuationShuttle01
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacesMxToPostTapingEvacuationShuttle01/LayerEvacuation", ReplyAction="http://tempuri.org/IInterfacesMxToPostTapingEvacuationShuttle01/LayerEvacuationRe" +
            "sponse")]
        void LayerEvacuation(evacuationns.PostTapingEvacuationShuttleLayerEvacuationRequest request);
    }
}
