//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_Lima.EvacuationShuttleToMx {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostTapingEvacuationShuttleMissionStatusRequest", Namespace="http://schemas.datacontract.org/2004/07/Mx.Broker.Std.Request.Interface.PostTapin" +
        "gEvacuationShuttle01")]
    [System.SerializableAttribute()]
    public partial class PostTapingEvacuationShuttleMissionStatusRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MissionNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_Lima.EvacuationShuttleToMx.PostTapingEvacuationShuttleMissionStatusType MissionStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MissionNumber {
            get {
                return this.MissionNumberField;
            }
            set {
                if ((this.MissionNumberField.Equals(value) != true)) {
                    this.MissionNumberField = value;
                    this.RaisePropertyChanged("MissionNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_Lima.EvacuationShuttleToMx.PostTapingEvacuationShuttleMissionStatusType MissionStatus {
            get {
                return this.MissionStatusField;
            }
            set {
                if ((this.MissionStatusField.Equals(value) != true)) {
                    this.MissionStatusField = value;
                    this.RaisePropertyChanged("MissionStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostTapingEvacuationShuttleMissionStatusType", Namespace="http://schemas.datacontract.org/2004/07/Mx.Broker.Std.Request.Interface.PostTapin" +
        "gEvacuationShuttle01")]
    public enum PostTapingEvacuationShuttleMissionStatusType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ok = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nok = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostTapingEvacuationShuttleReportRunningModeRequest", Namespace="http://schemas.datacontract.org/2004/07/Mx.Broker.Std.Request.Interface.PostTapin" +
        "gEvacuationShuttle01")]
    [System.SerializableAttribute()]
    public partial class PostTapingEvacuationShuttleReportRunningModeRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DefaultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DefaultLabelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EquipmentCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_Lima.EvacuationShuttleToMx.PostTapingEvacuationShuttleRunningModeType RunningModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RunningModeDateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DefaultCode {
            get {
                return this.DefaultCodeField;
            }
            set {
                if ((this.DefaultCodeField.Equals(value) != true)) {
                    this.DefaultCodeField = value;
                    this.RaisePropertyChanged("DefaultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultLabel {
            get {
                return this.DefaultLabelField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultLabelField, value) != true)) {
                    this.DefaultLabelField = value;
                    this.RaisePropertyChanged("DefaultLabel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EquipmentCode {
            get {
                return this.EquipmentCodeField;
            }
            set {
                if ((this.EquipmentCodeField.Equals(value) != true)) {
                    this.EquipmentCodeField = value;
                    this.RaisePropertyChanged("EquipmentCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_Lima.EvacuationShuttleToMx.PostTapingEvacuationShuttleRunningModeType RunningMode {
            get {
                return this.RunningModeField;
            }
            set {
                if ((this.RunningModeField.Equals(value) != true)) {
                    this.RunningModeField = value;
                    this.RaisePropertyChanged("RunningMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RunningModeDateTime {
            get {
                return this.RunningModeDateTimeField;
            }
            set {
                if ((this.RunningModeDateTimeField.Equals(value) != true)) {
                    this.RunningModeDateTimeField = value;
                    this.RaisePropertyChanged("RunningModeDateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostTapingEvacuationShuttleRunningModeType", Namespace="http://schemas.datacontract.org/2004/07/Mx.Broker.Std.Request.Interface.PostTapin" +
        "gEvacuationShuttle01")]
    public enum PostTapingEvacuationShuttleRunningModeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Manual = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rest = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissionInProgress = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Default = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EvacuationShuttleToMx.IInterfacesPostTapingEvacuationShuttleToMx01")]
    public interface IInterfacesPostTapingEvacuationShuttleToMx01 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacesPostTapingEvacuationShuttleToMx01/MissionStatus", ReplyAction="http://tempuri.org/IInterfacesPostTapingEvacuationShuttleToMx01/MissionStatusResp" +
            "onse")]
        void MissionStatus(Client_Lima.EvacuationShuttleToMx.PostTapingEvacuationShuttleMissionStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacesPostTapingEvacuationShuttleToMx01/MissionStatus", ReplyAction="http://tempuri.org/IInterfacesPostTapingEvacuationShuttleToMx01/MissionStatusResp" +
            "onse")]
        System.Threading.Tasks.Task MissionStatusAsync(Client_Lima.EvacuationShuttleToMx.PostTapingEvacuationShuttleMissionStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacesPostTapingEvacuationShuttleToMx01/ReportRunningMode" +
            "", ReplyAction="http://tempuri.org/IInterfacesPostTapingEvacuationShuttleToMx01/ReportRunningMode" +
            "Response")]
        void ReportRunningMode(Client_Lima.EvacuationShuttleToMx.PostTapingEvacuationShuttleReportRunningModeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterfacesPostTapingEvacuationShuttleToMx01/ReportRunningMode" +
            "", ReplyAction="http://tempuri.org/IInterfacesPostTapingEvacuationShuttleToMx01/ReportRunningMode" +
            "Response")]
        System.Threading.Tasks.Task ReportRunningModeAsync(Client_Lima.EvacuationShuttleToMx.PostTapingEvacuationShuttleReportRunningModeRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInterfacesPostTapingEvacuationShuttleToMx01Channel : Client_Lima.EvacuationShuttleToMx.IInterfacesPostTapingEvacuationShuttleToMx01, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InterfacesPostTapingEvacuationShuttleToMx01Client : System.ServiceModel.ClientBase<Client_Lima.EvacuationShuttleToMx.IInterfacesPostTapingEvacuationShuttleToMx01>, Client_Lima.EvacuationShuttleToMx.IInterfacesPostTapingEvacuationShuttleToMx01 {
        
        public InterfacesPostTapingEvacuationShuttleToMx01Client() {
        }
        
        public InterfacesPostTapingEvacuationShuttleToMx01Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InterfacesPostTapingEvacuationShuttleToMx01Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfacesPostTapingEvacuationShuttleToMx01Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfacesPostTapingEvacuationShuttleToMx01Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void MissionStatus(Client_Lima.EvacuationShuttleToMx.PostTapingEvacuationShuttleMissionStatusRequest request) {
            base.Channel.MissionStatus(request);
        }
        
        public System.Threading.Tasks.Task MissionStatusAsync(Client_Lima.EvacuationShuttleToMx.PostTapingEvacuationShuttleMissionStatusRequest request) {
            return base.Channel.MissionStatusAsync(request);
        }
        
        public void ReportRunningMode(Client_Lima.EvacuationShuttleToMx.PostTapingEvacuationShuttleReportRunningModeRequest request) {
            base.Channel.ReportRunningMode(request);
        }
        
        public System.Threading.Tasks.Task ReportRunningModeAsync(Client_Lima.EvacuationShuttleToMx.PostTapingEvacuationShuttleReportRunningModeRequest request) {
            return base.Channel.ReportRunningModeAsync(request);
        }
    }
}
