/* soapBasicHttpBinding_USCOREIInterfacesPostTapingCollectShuttleToMx01Proxy.h
   Generated by gSOAP 2.8.100 for client_collect.h

gSOAP XML Web services tools
Copyright (C) 2000-2020, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapBasicHttpBinding_USCOREIInterfacesPostTapingCollectShuttleToMx01Proxy_H
#define soapBasicHttpBinding_USCOREIInterfacesPostTapingCollectShuttleToMx01Proxy_H
#include "soapH.h"

    class SOAP_CMAC BasicHttpBinding_USCOREIInterfacesPostTapingCollectShuttleToMx01Proxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        /// flag indicating that this context is owned by this proxy and should be deleted by the destructor
        bool soap_own;
        /// Endpoint URL of service 'BasicHttpBinding_USCOREIInterfacesPostTapingCollectShuttleToMx01Proxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in client_collect.h, if any
        /// Construct a proxy with new managing context
        BasicHttpBinding_USCOREIInterfacesPostTapingCollectShuttleToMx01Proxy();
        /// Copy constructor
        BasicHttpBinding_USCOREIInterfacesPostTapingCollectShuttleToMx01Proxy(const BasicHttpBinding_USCOREIInterfacesPostTapingCollectShuttleToMx01Proxy& rhs);
        /// Construct proxy given a shared managing context
        BasicHttpBinding_USCOREIInterfacesPostTapingCollectShuttleToMx01Proxy(struct soap*);
        /// Construct proxy given a shared managing context and endpoint URL
        BasicHttpBinding_USCOREIInterfacesPostTapingCollectShuttleToMx01Proxy(struct soap*, const char *soap_endpoint_url);
        /// Constructor taking an endpoint URL
        BasicHttpBinding_USCOREIInterfacesPostTapingCollectShuttleToMx01Proxy(const char *soap_endpoint_url);
        /// Constructor taking input and output mode flags for the new managing context
        BasicHttpBinding_USCOREIInterfacesPostTapingCollectShuttleToMx01Proxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        BasicHttpBinding_USCOREIInterfacesPostTapingCollectShuttleToMx01Proxy(const char *soap_endpoint_url, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        BasicHttpBinding_USCOREIInterfacesPostTapingCollectShuttleToMx01Proxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and its managing context, when the context was allocated by the constructor
        virtual ~BasicHttpBinding_USCOREIInterfacesPostTapingCollectShuttleToMx01Proxy();
        /// Initializer used by constructors
        virtual void BasicHttpBinding_USCOREIInterfacesPostTapingCollectShuttleToMx01Proxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual BasicHttpBinding_USCOREIInterfacesPostTapingCollectShuttleToMx01Proxy *copy();
        /// Copy assignment
        BasicHttpBinding_USCOREIInterfacesPostTapingCollectShuttleToMx01Proxy& operator=(const BasicHttpBinding_USCOREIInterfacesPostTapingCollectShuttleToMx01Proxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault subcode QName string (NULL when absent)
        virtual const char *soap_fault_subcode();
        /// Get SOAP Fault string/reason (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail XML string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        //
        /// Web service synchronous operation 'TapingOutputConveyorNumber' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int TapingOutputConveyorNumber(_ns1__TapingOutputConveyorNumber *ns1__TapingOutputConveyorNumber, _ns1__TapingOutputConveyorNumberResponse &ns1__TapingOutputConveyorNumberResponse) { return this->TapingOutputConveyorNumber(NULL, NULL, ns1__TapingOutputConveyorNumber, ns1__TapingOutputConveyorNumberResponse); }
        /// Web service synchronous operation 'TapingOutputConveyorNumber' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int TapingOutputConveyorNumber(const char *soap_endpoint_url, const char *soap_action, _ns1__TapingOutputConveyorNumber *ns1__TapingOutputConveyorNumber, _ns1__TapingOutputConveyorNumberResponse &ns1__TapingOutputConveyorNumberResponse) { return this->send_TapingOutputConveyorNumber(soap_endpoint_url, soap_action, ns1__TapingOutputConveyorNumber) || this->recv_TapingOutputConveyorNumber(ns1__TapingOutputConveyorNumberResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_TapingOutputConveyorNumber' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_TapingOutputConveyorNumber(const char *soap_endpoint_url, const char *soap_action, _ns1__TapingOutputConveyorNumber *ns1__TapingOutputConveyorNumber);
        /// Web service asynchronous operation 'recv_TapingOutputConveyorNumber' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_TapingOutputConveyorNumber(_ns1__TapingOutputConveyorNumberResponse &ns1__TapingOutputConveyorNumberResponse);
        //
        /// Web service synchronous operation 'MissionStatus' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int MissionStatus(_ns1__MissionStatus *ns1__MissionStatus, _ns1__MissionStatusResponse &ns1__MissionStatusResponse) { return this->MissionStatus(NULL, NULL, ns1__MissionStatus, ns1__MissionStatusResponse); }
        /// Web service synchronous operation 'MissionStatus' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int MissionStatus(const char *soap_endpoint_url, const char *soap_action, _ns1__MissionStatus *ns1__MissionStatus, _ns1__MissionStatusResponse &ns1__MissionStatusResponse) { return this->send_MissionStatus(soap_endpoint_url, soap_action, ns1__MissionStatus) || this->recv_MissionStatus(ns1__MissionStatusResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_MissionStatus' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_MissionStatus(const char *soap_endpoint_url, const char *soap_action, _ns1__MissionStatus *ns1__MissionStatus);
        /// Web service asynchronous operation 'recv_MissionStatus' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_MissionStatus(_ns1__MissionStatusResponse &ns1__MissionStatusResponse);
        //
        /// Web service synchronous operation 'ReportRunningMode' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int ReportRunningMode(_ns1__ReportRunningMode *ns1__ReportRunningMode, _ns1__ReportRunningModeResponse &ns1__ReportRunningModeResponse) { return this->ReportRunningMode(NULL, NULL, ns1__ReportRunningMode, ns1__ReportRunningModeResponse); }
        /// Web service synchronous operation 'ReportRunningMode' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int ReportRunningMode(const char *soap_endpoint_url, const char *soap_action, _ns1__ReportRunningMode *ns1__ReportRunningMode, _ns1__ReportRunningModeResponse &ns1__ReportRunningModeResponse) { return this->send_ReportRunningMode(soap_endpoint_url, soap_action, ns1__ReportRunningMode) || this->recv_ReportRunningMode(ns1__ReportRunningModeResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_ReportRunningMode' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_ReportRunningMode(const char *soap_endpoint_url, const char *soap_action, _ns1__ReportRunningMode *ns1__ReportRunningMode);
        /// Web service asynchronous operation 'recv_ReportRunningMode' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_ReportRunningMode(_ns1__ReportRunningModeResponse &ns1__ReportRunningModeResponse);
    };
#endif